### ISSUE TITLE
:before :after not working

### ISSUE THREAD

**Issue by galadril** [basvdijk/domoticz-osidark-theme#1]
Any idea why :before and :after is not working?

I don't see the arrow for the buttons for example:
![before](https://cloud.githubusercontent.com/assets/14561640/21159141/461b9462-c180-11e6-9f88-23d8c73b3efa.png)

Tried on Firefox, Chrome, and IE and doesn't work on any of them??

**Comment by basvdijk** [comment]
The arrows are made by FontAwesome which I included via css. On which browser are you testing? On Chrome on a Mac they are there

![image](https://cloud.githubusercontent.com/assets/644550/21159855/ff77223a-c182-11e6-8b3e-7934b04df2f3.png)

**Comment by galadril** [comment]
im on windows 10.. 

tried firefox, ie, and chrome

**Comment by galadril** [comment]
you add the character in front of the button via :before and : after.. but it looks like that doesn;t work for me

**Comment by basvdijk** [comment]
That is very weird these browsers support :before and :after for sure. I am working on OSX. Will see if I can check Windows...

**Comment by basvdijk** [comment]
I've changed the external calls for fonts and css to https in https://github.com/basvdijk/domoticz-osidark-theme/blob/master/src/OsiDark/custom.css could you please see if this fixes your issue?

**Comment by galadril** [comment]
if looks like it works with your latest commit!

**Comment by basvdijk** [comment]
Nice 👍
