### ISSUE TITLE
White dialog on add manual switch

### ISSUE THREAD

**Issue by galadril** [basvdijk/domoticz-osidark-theme#10]
I think that the white design of your manual add switch dialog breaks your dark theme.
It may look better dark styled

![scrollbars](https://cloud.githubusercontent.com/assets/14561640/21185348/9a5a09e2-c210-11e6-905c-efda5aed8656.png)

```
.ui-dialog-buttonpane,
.ui-dialog {
	padding: 0;
	background: #212121;
	border: 1px solid #212121;
	color: white;
	position: relative;
	margin: 15px auto;    
	overflow: visible; !important
}


.ui-dialog-content
{
	color:white;
}
```

**Comment by galadril** [comment]
See my commits for the dark dialog
https://github.com/galadril/domoticz-osidark-theme/commits/master

**Comment by basvdijk** [comment]
Thanks, but I keep it light. The dark background and the black alpha background are too close to each other. I prefer a higher contrast.
