### ISSUE TITLE
Buttons on Event page not styled

### ISSUE THREAD

**Issue by galadril** [basvdijk/domoticz-osidark-theme#11]
Buttons on Event page not styled

![events](https://cloud.githubusercontent.com/assets/14561640/21186011/4442ddba-c213-11e6-8184-ccd31634b92b.png)

**Comment by basvdijk** [comment]
Unfortunately this view is an iframe. The css can not reach inside an iframe, therefore it can't be fixed without Javascript.

**Comment by galadril** [comment]
👎

**Comment by basvdijk** [comment]
I assume you make this sign regarding an iframe not allowing to change styles inside? ;)

**Comment by galadril** [comment]
yeah i hate iframes :)
