### ISSUE TITLE
css padding of some devices last seen tags

### ISSUE THREAD

**Issue by galadril** [basvdijk/domoticz-osidark-theme#3]
Some of the devices have weird padding on the last seen text
![device](https://cloud.githubusercontent.com/assets/14561640/21159290/f2e5564c-c180-11e6-897b-d86f12ca7c0b.png)

![untitled](https://cloud.githubusercontent.com/assets/14561640/21159337/1fd0405e-c181-11e6-9659-99329c727ac2.png)

**Comment by basvdijk** [comment]
Interesting, it looks like it has something todo with pressure / wind sensors. I don't have these which is why I probably didn't noticed. I'm gonna look into it.
