### ISSUE TITLE
update popup never collapse

### ISSUE THREAD

**Issue by galadril** [basvdijk/domoticz-osidark-theme#6]
This morning my domoticz system received a new update, but I don't want to be forced to install the update right away..

But the popup never moves out of the way.. and it hovers above all the buttons.
So im now forced to update :-)

![popup](https://cloud.githubusercontent.com/assets/14561640/21171593/63e790a2-c1cd-11e6-9326-2bda15298091.png)

**Comment by basvdijk** [comment]
You can click the green area to cancel the popup. Domoticz doesn't add a cancel button.
